### ISSUE TITLE
TomHarling/BIO_Solutions deleted?

### ISSUE THREAD

**Issue by 0oj** [matthewelse/british-informatics-olympiad#1]
Hi.
I'm looking for solutions for BIO 2014 Level 1.
Many repositories have skipped 2014.
I got to know TomHarling/BIO_Solutions had 2014 but the repository seems to be deleted now.

**Comment by matthewelse** [comment]
Hi,

Yeah it does look like those solutions have been deleted :(.

I've added a solution to 2014 Q1 in 1fa260e (see [here](https://github.com/matthewelse/british-informatics-olympiad/blob/master/2014/q1.py)).

**Comment by 0oj** [comment]
Thank you!

I just completed the 2014 paper correctly and would love to add the rest of the solutions here!
They might be helpful for other people like me in the future :D

If you think this is a good idea, I'll submit a PR.

**Comment by matthewelse** [comment]
Sure, go for it!
