### ISSUE TITLE
2020 Vision Not Working

### ISSUE THREAD

**Issue by Tom8520** [matthewelse/british-informatics-olympiad#4]
I am trying to test my code against yours to check that it works and am generating random ( valid ) test data. I have found a few examples that do not produce an output in your code but are valid inputs.

This is an example of those inputs:
28 44
990139 113312 357119 -623623 213319 308814 728373 54551 -581785 466899 -251743 -39328 8765 410924 92763 -21405 -939333 -28749 912718 -518718 951919 206261 -492846 -316903 637186 543719 982889 727487 
47 2 33 19 37 35 17 38 43 19 47 14 53 39 37 37 30 5 26 31 2 20 6 9 53 13 9 5 50 37 24 8 31 24 35 7 42 3 53 44 4 24 31 44

**Comment by 0oj** [comment]
I tried this input against my solution  (#3); is `666735333` the correct answer?

**Comment by Tom8520** [comment]
I think so ( thats what my program produced but I am not entirely sure if mine is correct ). Since you got the same answer using a different approach i think its safe to assume that it is correct.

**Comment by matthewelse** [comment]
Sorry for the slow response - for what it's worth, I'm pretty sure my solution is wrong, so I'll take a look at @OojAmit's PR.

**Comment by matthewelse** [comment]
I've finally had time to look at this properly, and managed to convince myself that the greedy algorithm @OojAmit wrote is correct, and I came up with an alternative solution that also seems to be correct. I also think that the C++ solution is trivially correct, but way too slow for any non-trivial problems. I'm going to tidy everything up, and then merge #3 .
